// Copyright (c) 2014 VigLink
/*
 VigLink JavaScript Library -- http://www.viglink.com

 Permission is hereby granted to create derivative works, but only for use
 with the VigLink web service.

 Includes:

 Sizzle CSS Selector Engine v1.10.20-pre
 http://sizzlejs.com/

 Copyright 2013 jQuery Foundation, Inc. and other contributors
 Released under the MIT license
 http://jquery.org/license

 Date: 2014-05-22
*/
(function(m){var h,c={_breaker:{},each:function(a,b){var d,e;if("object"===c.type(a)&&a.hasOwnProperty)for(d in a){if(a.hasOwnProperty(d)&&b(a[d],d)===c._breaker)break}else if(a){d=0;for(e=a.length;d<e&&b(a[d],d)!==c._breaker;d++);}},extend:function(a){var b,d,c,f,g=arguments.length;a=a||{};for(d=1;d<g;d++)if(f=arguments[d],void 0!==f&&null!==f)for(c in f)b=f[c],a!==b&&void 0!==b&&(a[c]=b);return a},noop:function(){},type:function(){var a=function(a,d){try{return("function"===typeof window[d]||"object"===
typeof window[d])&&a instanceof window[d]}catch(c){}return!1};return function(b){return null===b?"null":void 0===b?"undefined":a(b,"HTMLElement")||"object"===typeof b&&1===b.nodeType&&"string"===typeof b.nodeName?"element":b==b.window?"window":a(b,"HTMLDocument")||"object"===typeof b&&("defaultView"in b||"parentWindow"in b)?"document":Object.prototype.toString.call(b).slice(8,-1).toLowerCase()}}()};c.extend(c,{addClass:function(a,b){c.hasClass(a,b)||(a.className=(a.className?a.className+" ":"")+b)},
attrValues:function(a,b,d){return(b=a[b])?b.split(d||" "):[]},batchable:function(a){a=c.extend({batch:c.noop,single:c.noop,timeout:100},a);var b=[],d=c.traits.cors&&c.traits.json,e=null,f=function(){null!==e&&(clearTimeout(e),e=null);1===b.length?a.single.apply(this,b[0]):1<b.length&&a.batch(b);b=[]},g=function(){b.push(c.toArray(arguments));d?null===e&&(e=setTimeout(c.bind(function(){f()},this),a.timeout)):f()};c.extend(g,{flush:f,now:a.single});return g},bind:function(a,b){return function(){return a.apply(b,
arguments)}},cache:function(){var a={},b="vglnk_"+(new Date).getTime(),d=0;return function(c,f,g){if(c){var l=c[b];if(l||void 0!==g)return l||(l=++d),a[l]||(c[b]=l,a[l]={}),void 0!==g&&(a[l][f]=g),"string"===typeof f?a[l][f]:a[l]}}}(),canonicalizeHostname:function(a){"string"===typeof a&&(a=c.createA(a));return a.hostname?a.hostname.toString().toLowerCase().replace(/^www\./,"").replace(/:.*$/,""):""},clone:function(a){return c.extend({},a)},contains:function(a,b){return-1!==c.indexOf(a,b)},context:function(a){"element"===
c.type(a)&&(a=a.ownerDocument);"document"===c.type(a)&&(a=a.defaultView||a.parentWindow);if("window"===c.type(a))return a},containsPII:function(a){return/\b[A-Z0-9._%+-]+(?:%(?:25)*40|@)[A-Z0-9.-]+\.[A-Z]{2,4}\b/i.test(a)},contextIsAncestor:function(a,b){for(var d=a.self;d.parent&&d.parent!==d;)if(d=d.parent,d===b)return!0;return!1},cors:function(a,b,d){var c,f=function(){d?d(c.responseText):eval(c.responseText)};c=new window.XMLHttpRequest;c.onreadystatechange=function(){4===c.readyState&&200===
c.status&&f()};try{return c.open("POST",a),c.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),c.withCredentials=!0,c.send(b),!0}catch(g){return!1}},createA:function(a,b){return c.createEl("a",{href:a,target:b})},createEl:function(a,b,d,e){var f;a=(e||document).createElement(a);b=b||{};d=d||{};for(f in b)void 0!==b[f]&&(a[f]=b[f]);c.css(a,d);return a},css:function(a,b){for(var d in b)try{a.style[d]=b[d]}catch(c){}return a},destructing:function(a){return function(a){var d=!1,c;return function(){d||
(c=a.apply(null,arguments),d=!0);return c}}(a)},escapeRegExp:function(){var a;return function(b){a=a||/([.*+?^${}()|[\]\\])/g;return b.replace(a,"\\$1")}}(),eventLink:function(a){var b,d=a.target||a.srcElement;do{try{b=d.nodeType}catch(c){break}if(1===b&&(a=d.tagName.toUpperCase(),"A"===a||"AREA"===a))return d;d=d.parentNode}while(d)},exceptionLogger:function(){var a=!1,b=c.noop;return function(c,e){if(void 0!==e)a=e,b=c;else return function(){if(a)try{return c.apply(this,arguments)}catch(e){b(e)}else return c.apply(this,
arguments)}}}(),find:function(a,b){var d;c.each(a,function(a,f){if(b(a,f))return d=a,c._breaker});return d},generateNodeFilter:function(){var a=function(a,c){var f,g;c=","+c.join(",")+",";f=0;for(g=a.length;f<g;f++)if(b(a[f],c))return!0;return!1},b=function(a,b){return-1!==b.indexOf(","+a+",")};return function(d){d=c.extend({custom:null,classes:[],rels:[],tags:[]},d);d.tags.length&&(d.tags=","+d.tags.join(",").toLowerCase()+",");return function(e,f){f=c.extend({ancestors:!0,self:!0},f);var g=!0,l=
!0,h=function(e,f){var g;if(g=!(d.tags.length&&b(e.nodeName.toLowerCase(),d.tags))){if(g=d.classes.length){g=d.classes;var l=c.attrValues(e,"className");g=a(g,l)}if(g=!g){if(g=d.rels.length)g=d.rels,l=c.attrValues(e,"rel"),g=b(e.nodeName.toLowerCase(),",a,")&&a(g,l);g=!g&&!("function"===c.type(d.custom)&&d.custom(e,f))}}return g},l=!f.self||h(e,!0);if(f.ancestors)for(;e.parentNode;)if(e=e.parentNode,1===e.nodeType&&!h(e,!1)){g=!1;break}return l&&g}}}(),fromJSON:function(a){if(c.traits.json)try{return window.JSON.parse(a)}catch(b){}},
fromQuery:function(a){"?"===a.substr(0,1)&&(a=a.substr(1));a=a.split("&");var b={};c.each(a,function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])});return b},geometry:function(){var a,b=arguments.length,d=Infinity,e=Infinity,f=-Infinity,g=-Infinity,l;for(a=0;a<b;a++)l=c.position(arguments[a]),d=Math.min(d,l.x),e=Math.min(e,l.y),f=Math.max(f,l.x+arguments[a].offsetWidth),g=Math.max(g,l.y+arguments[a].offsetHeight);return{x:d,y:e,w:f-d,h:g-e,x1:d,y1:e,x2:f,y2:g}},getActualHref:function(a){return c.cache(a,
"href")||a.href},hasAttrValue:function(a,b,d,e){return b?c.contains(c.attrValues(a,b,e),d):!1},hasClass:function(a,b){return c.hasAttrValue(a,"className",b)},hasRel:function(a,b){return c.hasAttrValue(a,"rel",b)},indexOf:function(){return Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b)}:function(a,b){var c,e;c=0;for(e=a.length;c<e;c++)if(a[c]===b)return c;return-1}}(),isArray:function(a){return"array"===c.type(a)},isDefaultPrevented:function(a){return a.isDefaultPrevented&&
a.isDefaultPrevented()||!1===a.returnValue||!0===a.defaultPrevented},jsonp:function(a){var b=document.getElementsByTagName("script")[0];a=c.createEl("script",{type:"text/javascript",src:a});b.parentNode.insertBefore(a,b)},map:function(a,b){var d=[];c.each(a,function(a,c){void 0!==a&&(d[c]=b(a))});return d},matches:function(){try{return this.Sizzle.matchesSelector.apply(this.Sizzle,arguments)}catch(a){return!0}},on:function(){var a;return function(b,d,e){var f,g;if(1===arguments.length)a=b;else{if(2===
arguments.length){if(!a)return;e=d;d=b;b=a}try{f=b["on"+d]}catch(l){}"function"===typeof f&&(b["on"+d]=c.bind(function(a){a=a||window.event;var d=f.apply(b,arguments);this.exceptionLogger(function(){return a?(void 0!==d&&!1!==a.returnValue&&(a.returnValue=d),c.isDefaultPrevented(a)&&"function"===c.type(a.preventDefault)&&a.preventDefault(),a.returnValue):d})()},this));g=c.exceptionLogger(function(){if(a.enabled())return e.apply(null,arguments)});b.addEventListener?b.addEventListener(d,g,!1):b.attachEvent&&
b.attachEvent("on"+d,g)}}}(),position:function(a,b){var c,e=0,f=0,g=0,l=0;b=b||document;if(!a.offsetParent)return!1;c=a;do e+=c.offsetLeft,f+=c.offsetTop,c=c.offsetParent;while(c);c=a;do g+=c.scrollLeft,l+=c.scrollTop,c=c.parentNode;while(c&&c!==b.body);return{x:e-g,y:f-l}},preventDefault:function(a){a.preventDefault&&a.preventDefault();return a.returnValue=!1},prune:function(a){c.each(a,function(b,c){(null===b||void 0===b)&&delete a[c]});return a},ready:function(){var a=!1,b=[],d=!1,e,f,g,l,h;document.addEventListener?
g=function(){document.removeEventListener("DOMContentLoaded",g,!1);h()}:document.attachEvent&&(l=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",l),h())});e=function(){if(!a){a=!0;if("interactive"===document.readyState||"complete"===document.readyState)return h();if(document.addEventListener)document.addEventListener("DOMContentLoaded",g,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",l);var b=!1;try{b=null===window.frameElement}catch(d){}document.documentElement.doScroll&&
b&&f()}c.on(window,"load",h)}};f=function(){if(!d){try{document.documentElement.doScroll("left")}catch(a){setTimeout(c.exceptionLogger(f),1);return}h()}};h=function(){if(!d){if(!document.body)return setTimeout(c.exceptionLogger(h),13);d=!0;b&&(c.each(b,function(a){a()}),b=null)}};return function(a){e();d?a():b.push(a)}}(),reformatKeys:function(a){var b,d,e=function(a){return"_"+a.toLowerCase()};for(b in a)d=b.replace(/([A-Z])/g,e),"object"===c.type(a[b])&&(a[b]=c.reformatKeys(a[b])),d!==b&&(a[d]=
a[b],delete a[b]);return a},removeClass:function(a,b){if(c.hasClass(a,b)){var d,e,f=c.attrValues(a,"className");d=0;for(e=f.length;d<e;d++)f[d]===b&&delete f[d];a.className=f.join(" ")}},request:function(a,b,d){var e,f;d=c.extend({fn:c.noop,jsonp:!0,"return":!1,timeout:null},d);"string"===typeof d.fn?(e=window[d.fn],f=d.fn):"function"===typeof d.fn&&(!0!==d.jsonp?e=d.fn:(e=c.destructing(d.fn),f=c.uniqid("vglnk_jsonp_"),window[f]=c.exceptionLogger(function(){e.apply(this,arguments);window[f]=void 0}),
null!==d.timeout&&setTimeout(c.exceptionLogger(e),d.timeout)));f&&(b=c.extend({format:"jsonp",jsonp:f},b));b=c.toQuery(b);return d["return"]?a+(b.length?"?":"")+b:c.traits.cors&&c.cors(a,b,d.jsonp?null:e)?!0:c.jsonp(a+(b.length?"?":"")+b)},select:function(){try{return this.Sizzle.apply(this.Sizzle,arguments)}catch(a){return[]}},toArray:function(a){if(a&&void 0!==a.length)try{return Array.prototype.slice.call(a,0)}catch(b){var c,e,f=[];c=0;for(e=a.length;c<e;c++)f[c]=a[c];return f}},toJSON:function(a){if(c.traits.json)try{return window.JSON.stringify(a)}catch(b){}},
toQuery:function(a){var b="";c.each(c.prune(a),function(a,c){b+="&"+encodeURIComponent(c)+"="+encodeURIComponent(a)});return b.substr(1)},transmitsPII:function(a){return c.containsPII(a+" "+document.referrer)},updateUrl:function(a,b){return c.extend(c.createA(a),b).href},uniqid:function(){var a=0;return function(b){return(b||"")+(new Date).getTime()+a++}}()});var w=function(){var a=c.find(c.toArray(arguments),function(a){return"function"===c.type(a)});a&&(c.Sizzle=a())};w.amd=!0;(function(a){function b(a,
b,c,d){var e,f,g,h,l;(b?b.ownerDocument||b:D)!==z&&K(b);b=b||z;c=c||[];if(!a||"string"!==typeof a)return c;if(1!==(h=b.nodeType)&&9!==h)return[];if(F&&!d){if(e=qa.exec(a))if(g=e[1])if(9===h)if((f=b.getElementById(g))&&f.parentNode){if(f.id===g)return c.push(f),c}else return c;else{if(b.ownerDocument&&(f=b.ownerDocument.getElementById(g))&&V(b,f)&&f.id===g)return c.push(f),c}else{if(e[2])return L.apply(c,b.getElementsByTagName(a)),c;if((g=e[3])&&v.getElementsByClassName&&b.getElementsByClassName)return L.apply(c,
b.getElementsByClassName(g)),c}if(v.qsa&&(!A||!A.test(a))){f=e=y;g=b;l=9===h&&a;if(1===h&&"object"!==b.nodeName.toLowerCase()){h=W(a);(e=b.getAttribute("id"))?f=e.replace(ra,"\\$&"):b.setAttribute("id",f);f="[id='"+f+"'] ";for(g=h.length;g--;)h[g]=f+r(h[g]);g=ea.test(a)&&u(b.parentNode)||b;l=h.join(",")}if(l)try{return L.apply(c,g.querySelectorAll(l)),c}catch(k){}finally{e||b.removeAttribute("id")}}}return ja(a.replace(Z,"$1"),b,c,d)}function c(){function a(c,d){b.push(c+" ")>s.cacheLength&&delete a[b.shift()];
return a[c+" "]=d}var b=[];return a}function e(a){a[y]=!0;return a}function f(a){var b=z.createElement("div");try{return!!a(b)}catch(c){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}}function g(a,b){for(var c=a.split("|"),d=a.length;d--;)s.attrHandle[c[d]]=b}function l(a,b){var c=b&&a,d=c&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||ka)-(~a.sourceIndex||ka);if(d)return d;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1}function h(a){return function(b){return"input"===b.nodeName.toLowerCase()&&
b.type===a}}function k(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function p(a){return e(function(b){b=+b;return e(function(c,d){for(var e,f=a([],c.length,b),g=f.length;g--;)if(c[e=f[g]])c[e]=!(d[e]=c[e])})})}function u(a){return a&&typeof a.getElementsByTagName!==R&&a}function m(){}function r(a){for(var b=0,c=a.length,d="";b<c;b++)d+=a[b].value;return d}function t(a,b,c){var d=b.dir,e=c&&"parentNode"===d,f=sa++;return b.first?function(b,c,
U){for(;b=b[d];)if(1===b.nodeType||e)return a(b,c,U)}:function(b,c,U){var B,g,h=[E,f];if(U)for(;b=b[d];){if((1===b.nodeType||e)&&a(b,c,U))return!0}else for(;b=b[d];)if(1===b.nodeType||e){g=b[y]||(b[y]={});if((B=g[d])&&B[0]===E&&B[1]===f)return h[2]=B[2];g[d]=h;if(h[2]=a(b,c,U))return!0}}}function n(a){return 1<a.length?function(b,c,d){for(var e=a.length;e--;)if(!a[e](b,c,d))return!1;return!0}:a[0]}function C(a,b,c,d,e){for(var f,g=[],h=0,l=a.length,k=null!=b;h<l;h++)if(f=a[h])if(!c||c(f,d,e))g.push(f),
k&&b.push(h);return g}function fa(a,c,d,f,g,h){f&&!f[y]&&(f=fa(f));g&&!g[y]&&(g=fa(g,h));return e(function(e,h,l,k){var p,u,m=[],da=[],r=h.length,x;if(!(x=e)){x=c||"*";for(var q=l.nodeType?[l]:l,t=[],s=0,v=q.length;s<v;s++)b(x,q[s],t);x=t}x=a&&(e||!c)?C(x,m,a,l,k):x;q=d?g||(e?a:r||f)?[]:h:x;d&&d(x,q,l,k);if(f){p=C(q,da);f(p,[],l,k);for(l=p.length;l--;)if(u=p[l])q[da[l]]=!(x[da[l]]=u)}if(e){if(g||a){if(g){p=[];for(l=q.length;l--;)if(u=q[l])p.push(x[l]=u);g(null,q=[],p,k)}for(l=q.length;l--;)if((u=
q[l])&&-1<(p=g?O.call(e,u):m[l]))e[p]=!(h[p]=u)}}else q=C(q===h?q.splice(r,q.length):q),g?g(null,h,q,k):L.apply(h,q)})}function ga(a){var b,c,d,e=a.length,f=s.relative[a[0].type];c=f||s.relative[" "];for(var g=f?1:0,h=t(function(a){return a===b},c,!0),l=t(function(a){return-1<O.call(b,a)},c,!0),k=[function(a,c,d){return!f&&(d||c!==$)||((b=c).nodeType?h(a,c,d):l(a,c,d))}];g<e;g++)if(c=s.relative[a[g].type])k=[t(n(k),c)];else{c=s.filter[a[g].type].apply(null,a[g].matches);if(c[y]){for(d=++g;d<e&&!s.relative[a[d].type];d++);
return fa(1<g&&n(k),1<g&&r(a.slice(0,g-1).concat({value:" "===a[g-2].type?"*":""})).replace(Z,"$1"),c,g<d&&ga(a.slice(g,d)),d<e&&ga(a=a.slice(d)),d<e&&r(a))}k.push(c)}return n(k)}function ta(a,c){var d=0<c.length,f=0<a.length,g=function(e,g,h,l,k){var p,u,q,m=0,H="0",x=e&&[],r=[],t=$,v=e||f&&s.find.TAG("*",k),Y=E+=null==t?1:Math.random()||0.1,n=v.length;for(k&&($=g!==z&&g);H!==n&&null!=(p=v[H]);H++){if(f&&p){for(u=0;q=a[u++];)if(q(p,g,h)){l.push(p);break}k&&(E=Y)}d&&((p=!q&&p)&&m--,e&&x.push(p))}m+=
H;if(d&&H!==m){for(u=0;q=c[u++];)q(x,r,g,h);if(e){if(0<m)for(;H--;)!x[H]&&!r[H]&&(r[H]=ua.call(l));r=C(r)}L.apply(l,r);k&&(!e&&0<r.length&&1<m+c.length)&&b.uniqueSort(l)}k&&(E=Y,$=t);return x};return d?e(g):g}var S,v,s,aa,la,W,ha,ja,$,M,T,K,z,G,F,A,P,ba,V,y="sizzle"+-new Date,D=a.document,E=0,sa=0,ma=c(),na=c(),oa=c(),ia=function(a,b){a===b&&(T=!0);return 0},R="undefined",ka=-2147483648,va={}.hasOwnProperty,N=[],ua=N.pop,wa=N.push,L=N.push,pa=N.slice,O=N.indexOf||function(a){for(var b=0,c=this.length;b<
c;b++)if(this[b]===a)return b;return-1},Z=/^[\x20\t\r\n\f]+|((?:^|[^\\])(?:\\.)*)[\x20\t\r\n\f]+$/g,xa=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,ya=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,za=/=[\x20\t\r\n\f]*([^\]'"]*?)[\x20\t\r\n\f]*\]/g,Aa=RegExp(":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),
Ba=/^(?:\\.|[\w-]|[^\x00-\xa0])+$/,ca={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:/^((?:\\.|[\w-]|[^\x00-\xa0])+|[*])/,ATTR:RegExp("^\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\]"),PSEUDO:RegExp("^:((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),
CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)","i"),bool:RegExp("^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$","i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)",
"i")},Ca=/^(?:input|select|textarea|button)$/i,Da=/^h\d$/i,X=/^[^{]+\{\s*\[native \w/,qa=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,ea=/[+~]/,ra=/'|\\/g,I=/\\([\da-f]{1,6}[\x20\t\r\n\f]?|([\x20\t\r\n\f])|.)/ig,J=function(a,b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)};try{L.apply(N=pa.call(D.childNodes),D.childNodes),N[D.childNodes.length].nodeType}catch(Ea){L={apply:N.length?function(a,b){wa.apply(a,pa.call(b))}:function(a,b){for(var c=
a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}v=b.support={};la=b.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};K=b.setDocument=function(a){var b=a?a.ownerDocument||a:D;a=b.defaultView;if(b===z||9!==b.nodeType||!b.documentElement)return z;z=b;G=b.documentElement;F=!la(b);a&&a!==a.top&&(a.addEventListener?a.addEventListener("unload",function(){K()},!1):a.attachEvent&&a.attachEvent("onunload",function(){K()}));v.attributes=f(function(a){a.className="i";return!a.getAttribute("className")});
v.getElementsByTagName=f(function(a){a.appendChild(b.createComment(""));return!a.getElementsByTagName("*").length});v.getElementsByClassName=X.test(b.getElementsByClassName)&&f(function(a){a.innerHTML="<div class='a'></div><div class='a i'></div>";a.firstChild.className="i";return 2===a.getElementsByClassName("i").length});v.getById=f(function(a){G.appendChild(a).id=y;return!b.getElementsByName||!b.getElementsByName(y).length});v.getById?(s.find.ID=function(a,b){if(typeof b.getElementById!==R&&F){var c=
b.getElementById(a);return c&&c.parentNode?[c]:[]}},s.filter.ID=function(a){var b=a.replace(I,J);return function(a){return a.getAttribute("id")===b}}):(delete s.find.ID,s.filter.ID=function(a){var b=a.replace(I,J);return function(a){return(a=typeof a.getAttributeNode!==R&&a.getAttributeNode("id"))&&a.value===b}});s.find.TAG=v.getElementsByTagName?function(a,b){if(typeof b.getElementsByTagName!==R)return b.getElementsByTagName(a)}:function(a,b){var c,d=[],e=0,Q=b.getElementsByTagName(a);if("*"===a){for(;c=
Q[e++];)1===c.nodeType&&d.push(c);return d}return Q};s.find.CLASS=v.getElementsByClassName&&function(a,b){if(typeof b.getElementsByClassName!==R&&F)return b.getElementsByClassName(a)};P=[];A=[];if(v.qsa=X.test(b.querySelectorAll))f(function(a){a.innerHTML="<select msallowclip=''><option selected=''></option></select>";a.querySelectorAll("[msallowclip^='']").length&&A.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||A.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");
a.querySelectorAll(":checked").length||A.push(":checked")}),f(function(a){var c=b.createElement("input");c.setAttribute("type","hidden");a.appendChild(c).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&A.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");a.querySelectorAll(":enabled").length||A.push(":enabled",":disabled");a.querySelectorAll("*,:x");A.push(",.*:")});(v.matchesSelector=X.test(ba=G.matches||G.webkitMatchesSelector||G.mozMatchesSelector||G.oMatchesSelector||G.msMatchesSelector))&&
f(function(a){v.disconnectedMatch=ba.call(a,"div");ba.call(a,"[s!='']:x");P.push("!=",":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)")});A=A.length&&RegExp(A.join("|"));P=P.length&&RegExp(P.join("|"));
V=(a=X.test(G.compareDocumentPosition))||X.test(G.contains)?function(a,b){var c=9===a.nodeType?a.documentElement:a,d=b&&b.parentNode;return a===d||!(!d||!(1===d.nodeType&&(c.contains?c.contains(d):a.compareDocumentPosition&&a.compareDocumentPosition(d)&16)))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};ia=a?function(a,c){if(a===c)return T=!0,0;var d=!a.compareDocumentPosition-!c.compareDocumentPosition;if(d)return d;d=(a.ownerDocument||a)===(c.ownerDocument||c)?a.compareDocumentPosition(c):
1;return d&1||!v.sortDetached&&c.compareDocumentPosition(a)===d?a===b||a.ownerDocument===D&&V(D,a)?-1:c===b||c.ownerDocument===D&&V(D,c)?1:M?O.call(M,a)-O.call(M,c):0:d&4?-1:1}:function(a,c){if(a===c)return T=!0,0;var d,e=0;d=a.parentNode;var Q=c.parentNode,f=[a],g=[c];if(!d||!Q)return a===b?-1:c===b?1:d?-1:Q?1:M?O.call(M,a)-O.call(M,c):0;if(d===Q)return l(a,c);for(d=a;d=d.parentNode;)f.unshift(d);for(d=c;d=d.parentNode;)g.unshift(d);for(;f[e]===g[e];)e++;return e?l(f[e],g[e]):f[e]===D?-1:g[e]===
D?1:0};return b};b.matches=function(a,c){return b(a,null,null,c)};b.matchesSelector=function(a,c){(a.ownerDocument||a)!==z&&K(a);c=c.replace(za,"='$1']");if(v.matchesSelector&&F&&(!P||!P.test(c))&&(!A||!A.test(c)))try{var d=ba.call(a,c);if(d||v.disconnectedMatch||a.document&&11!==a.document.nodeType)return d}catch(e){}return 0<b(c,z,null,[a]).length};b.contains=function(a,b){(a.ownerDocument||a)!==z&&K(a);return V(a,b)};b.attr=function(a,b){(a.ownerDocument||a)!==z&&K(a);var c=s.attrHandle[b.toLowerCase()],
c=c&&va.call(s.attrHandle,b.toLowerCase())?c(a,b,!F):void 0;return void 0!==c?c:v.attributes||!F?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null};b.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};b.uniqueSort=function(a){var b,c=[],d=0,e=0;T=!v.detectDuplicates;M=!v.sortStable&&a.slice(0);a.sort(ia);if(T){for(;b=a[e++];)b===a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],1)}M=null;return a};aa=b.getText=function(a){var b,c="",d=0;if(b=a.nodeType)if(1===
b||9===b||11===b){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)c+=aa(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[d++];)c+=aa(b);return c};s=b.selectors={cacheLength:50,createPseudo:e,match:ca,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(I,J);a[3]=(a[3]||a[4]||a[5]||"").replace(I,J);"~="===
a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||b.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&b.error(a[0]);return a},PSEUDO:function(a){var b,c=!a[6]&&a[2];if(ca.CHILD.test(a[0]))return null;if(a[3])a[2]=a[4]||a[5]||"";else if(c&&Aa.test(c)&&(b=W(c,!0))&&(b=c.indexOf(")",c.length-b)-c.length))a[0]=a[0].slice(0,b),a[2]=c.slice(0,b);return a.slice(0,3)}},filter:{TAG:function(a){var b=
a.replace(I,J).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=ma[a+" "];return b||(b=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&ma(a,function(a){return b.test("string"===typeof a.className&&a.className||typeof a.getAttribute!==R&&a.getAttribute("class")||"")})},ATTR:function(a,c,d){return function(e){e=b.attr(e,a);if(null==e)return"!="===c;if(!c)return!0;e+="";return"="===c?e===d:"!="===c?
e!==d:"^="===c?d&&0===e.indexOf(d):"*="===c?d&&-1<e.indexOf(d):"$="===c?d&&e.slice(-d.length)===d:"~="===c?-1<(" "+e+" ").indexOf(d):"|="===c?e===d||e.slice(0,d.length+1)===d+"-":!1}},CHILD:function(a,b,c,d,e){var f="nth"!==a.slice(0,3),g="last"!==a.slice(-4),h="of-type"===b;return 1===d&&0===e?function(a){return!!a.parentNode}:function(b,c,l){var k,p,u,B,q;c=f!==g?"nextSibling":"previousSibling";var m=b.parentNode,x=h&&b.nodeName.toLowerCase();l=!l&&!h;if(m){if(f){for(;c;){for(p=b;p=p[c];)if(h?p.nodeName.toLowerCase()===
x:1===p.nodeType)return!1;q=c="only"===a&&!q&&"nextSibling"}return!0}q=[g?m.firstChild:m.lastChild];if(g&&l){l=m[y]||(m[y]={});k=l[a]||[];B=k[0]===E&&k[1];u=k[0]===E&&k[2];for(p=B&&m.childNodes[B];p=++B&&p&&p[c]||(u=B=0)||q.pop();)if(1===p.nodeType&&++u&&p===b){l[a]=[E,B,u];break}}else if(l&&(k=(b[y]||(b[y]={}))[a])&&k[0]===E)u=k[1];else for(;p=++B&&p&&p[c]||(u=B=0)||q.pop();)if((h?p.nodeName.toLowerCase()===x:1===p.nodeType)&&++u)if(l&&((p[y]||(p[y]={}))[a]=[E,u]),p===b)break;u-=e;return u===d||
0===u%d&&0<=u/d}}},PSEUDO:function(a,c){var d,f=s.pseudos[a]||s.setFilters[a.toLowerCase()]||b.error("unsupported pseudo: "+a);return f[y]?f(c):1<f.length?(d=[a,a,"",c],s.setFilters.hasOwnProperty(a.toLowerCase())?e(function(a,b){for(var d,e=f(a,c),g=e.length;g--;)d=O.call(a,e[g]),a[d]=!(b[d]=e[g])}):function(a){return f(a,0,d)}):f}},pseudos:{not:e(function(a){var b=[],c=[],d=ha(a.replace(Z,"$1"));return d[y]?e(function(a,b,c,e){e=d(a,null,e,[]);for(var f=a.length;f--;)if(c=e[f])a[f]=!(b[f]=c)}):
function(a,e,f){b[0]=a;d(b,null,f,c);return!c.pop()}}),has:e(function(a){return function(c){return 0<b(a,c).length}}),contains:e(function(a){a=a.replace(I,J);return function(b){return-1<(b.textContent||b.innerText||aa(b)).indexOf(a)}}),lang:e(function(a){Ba.test(a||"")||b.error("unsupported lang: "+a);a=a.replace(I,J).toLowerCase();return function(b){var c;do if(c=F?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&
1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===G},focus:function(a){return a===z.activeElement&&(!z.hasFocus||z.hasFocus())&&!(!a.type&&!a.href&&!~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;
return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!s.pseudos.empty(a)},header:function(a){return Da.test(a.nodeName)},input:function(a){return Ca.test(a.nodeName)},button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||"text"===b.toLowerCase())},first:p(function(){return[0]}),
last:p(function(a,b){return[b-1]}),eq:p(function(a,b,c){return[0>c?c+b:c]}),even:p(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),odd:p(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:p(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:p(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};s.pseudos.nth=s.pseudos.eq;for(S in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})s.pseudos[S]=h(S);for(S in{submit:!0,reset:!0})s.pseudos[S]=k(S);m.prototype=s.filters=
s.pseudos;s.setFilters=new m;W=b.tokenize=function(a,c){var d,e,f,g,l,h,k;if(l=na[a+" "])return c?0:l.slice(0);l=a;h=[];for(k=s.preFilter;l;){if(!d||(e=xa.exec(l)))e&&(l=l.slice(e[0].length)||l),h.push(f=[]);d=!1;if(e=ya.exec(l))d=e.shift(),f.push({value:d,type:e[0].replace(Z," ")}),l=l.slice(d.length);for(g in s.filter)if((e=ca[g].exec(l))&&(!k[g]||(e=k[g](e))))d=e.shift(),f.push({value:d,type:g,matches:e}),l=l.slice(d.length);if(!d)break}return c?l.length:l?b.error(a):na(a,h).slice(0)};ha=b.compile=
function(a,b){var c,d=[],e=[],f=oa[a+" "];if(!f){b||(b=W(a));for(c=b.length;c--;)f=ga(b[c]),f[y]?d.push(f):e.push(f);f=oa(a,ta(e,d));f.selector=a}return f};ja=b.select=function(a,b,c,d){var e,f,g,l,h="function"===typeof a&&a,k=!d&&W(a=h.selector||a);c=c||[];if(1===k.length){f=k[0]=k[0].slice(0);if(2<f.length&&"ID"===(g=f[0]).type&&v.getById&&9===b.nodeType&&F&&s.relative[f[1].type]){if(b=(s.find.ID(g.matches[0].replace(I,J),b)||[])[0])h&&(b=b.parentNode);else return c;a=a.slice(f.shift().value.length)}for(e=
ca.needsContext.test(a)?0:f.length;e--;){g=f[e];if(s.relative[l=g.type])break;if(l=s.find[l])if(d=l(g.matches[0].replace(I,J),ea.test(f[0].type)&&u(b.parentNode)||b)){f.splice(e,1);a=d.length&&r(f);if(!a)return L.apply(c,d),c;break}}}(h||ha(a,k))(d,b,!F,c,ea.test(a)&&u(b.parentNode)||b);return c};v.sortStable=y.split("").sort(ia).join("")===y;v.detectDuplicates=!!T;K();v.sortDetached=f(function(a){return a.compareDocumentPosition(z.createElement("div"))&1});f(function(a){a.innerHTML="<a href='#'></a>";
return"#"===a.firstChild.getAttribute("href")})||g("type|href|height|width",function(a,b,c){if(!c)return a.getAttribute(b,"type"===b.toLowerCase()?1:2)});(!v.attributes||!f(function(a){a.innerHTML="<input/>";a.firstChild.setAttribute("value","");return""===a.firstChild.getAttribute("value")}))&&g("value",function(a,b,c){if(!c&&"input"===a.nodeName.toLowerCase())return a.defaultValue});f(function(a){return null==a.getAttribute("disabled")})||g("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",
function(a,b,c){var d;if(!c)return!0===a[b]?b.toLowerCase():(d=a.getAttributeNode(b))&&d.specified?d.value:null});"function"===typeof w&&w.amd?w(function(){return b}):"undefined"!==typeof module&&module.exports?module.exports=b:a.Sizzle=b})(window);c.browser=function(){var a,b={},d=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,"$1; ").replace(/\;\s*$/,"").split(/;\s*/);c.each(d,function(c){a=(/[\/ :]([^\/ :]+)$/.exec(c)||[])[1];b[a?c.substr(0,c.length-a.length-
1).replace(/\d*$/,""):c]=a||!0});return{aol:b.aol,blackberry:b.blackberry,ie:b.msie,ios:b.mobile&&b.safari,opera:b.opera,playstation:b.playstation,version:parseFloat(b.version||b.crios||b.msie)||!1}}();c.platforms=function(){var a={bbp:{id_finder:["div",/^post-(\d+)$/],scope:"li .post"},hdlr:{id_finder:["div",/^post_(\d+)$/],scope:".post-content-area"},ipb:{id_finder:["div",/^post_id_(\d+)$/],scope:".post_body .post"},phpb:{id_finder:["div.post",/^p(\d+)$/],scope:".postbody .content,.postbody .signature"},
ubb:{id_finder:["a",/^Post(\d+)$/,"name"],scope:".post_inner *[id^='body'],.post_inner .signature"},vb3:{id_finder:["div[id], table[id],section[id]",/^post(\d+)$/],scope:"td[id^='td_post_'] div[id^='post_message_'],td[id^='td_post_'] div[id^='post_message_'] ~ div:not([class]),div[id^='td_post_'] div[id^='post_message_']"},vb4:{id_finder:["li",/^post_(\d+)$/],scope:".post-content,.postbody .content,.postbody .signature,ul.conversation-list .list-item-body"},wppr:{id_finder:["div",/^post-(\d+)$/],
scope:null}};return function(b){return c.extend(a[b]||{},{getPostIDs:function(){var a=[],b=this.id_finder;b&&c.each(c.select(b[0]),function(c){var g=b[2]||"id";(c=c[g]?c[g].match(b[1]):null)&&a.push(c[1])});return a.length?a:null}})}}();c.traits={basicCompatibility:!(c.browser.blackberry||c.browser.playstation),cors:window.XMLHttpRequest&&void 0!==(new window.XMLHttpRequest).withCredentials,crossWindowCommunication:!c.browser.ios,json:Boolean(window.JSON)&&Boolean(window.JSON.stringify)&&Boolean(window.JSON.parse),
jsRedirectSetsReferrer:c.browser.aol||!(c.browser.ie||c.browser.opera),quirksMode:!Boolean(window.addEventListener),windowLevelHandlers:Boolean(window.addEventListener)};var k,r,n,t;h={PLUGIN_MANUAL:1,TYPE_ACCEPTABLE:"l",api:function(){var a=function(a,b,f){f=f||{};b=c.extend(h.commonParams(a),b);b.subId&&b.key!==k.key&&(b.subId=null);return{method:a,opts:f,params:b}},b=function(a){return c.request(k.api_url+"/"+a.method,a.params,a.opts)};return c.batchable({batch:function(){var d=function(a,b){a=
c.fromJSON(a)||{};c.each(a,function(a,d){var e,h=b[d];a&&h&&("domains"===d&&"array"===c.type(a)&&(a={results:a}),a="string"===c.type(a)&&(e=a.match(/^[^(]+\((.*)\);?\s*$/))?c.fromJSON("["+e[1]+"]")||{}:[a],h.apply(window,a))})};return function(e){var f={},g={};c.each(e,function(b){b=a.apply(this,b);g[b.method]=b.opts.fn||c.noop;f[b.method]=c.prune(b.params)});b({method:"batch",params:c.extend(h.commonParams(),{batch:window.JSON.stringify(f)}),opts:{jsonp:!1,fn:function(a){d(a,g)}}})}}(),single:function(c,
e,f){c=a(c,e,f);return b(c)}})}(),addEventListener:function(a,b){this.fire(a,b)},click:function(){var a=function(a,b){if("_self"===b)return a;if(c.traits.crossWindowCommunication&&c.traits.jsRedirectSetsReferrer){var f=a.open("",b);f.focus();return f}},b=function(a){var b=a.previousSibling,f=a.nextSibling,g=["",a.textContent,""],l=function(a,b){for(var c=a,d=c.data;(c=c[b+"Sibling"])&&3===c.nodeType;)d+=c.data;return d},k=function(a,b,c){a=a.replace(/\s+/g," ");b=b.replace(/\s+/g," ");c=c.replace(/\s+/g,
" ");a=a.replace(/^\s+/,"");" "===b.substr(0,1)&&(b=b.substr(1),a+=" "!==a.substr(a.length-1,1)?" ":"");" "===b.substr(b.length-1,1)&&(b=b.substr(0,b.length-1),c=(" "!==c.substr(0,1)?" ":"")+c);c=c.replace(/\s+$/,"");return[a,b,c]};void 0!==g[1]&&(g[0]=b&&3===b.nodeType?l(b,"previous"):"",g[2]=f&&3===f.nodeType?l(f,"next"):"",g=k.apply(this,g),""!==g[0]&&""!==g[2]&&(g[0]=g[0].split(" ").reverse().slice(0,10+(" "===g[0].substr(g[0].length-1,1)?1:0)).reverse().join(" "),g[2]=g[2].split(" ").slice(0,
10).join(" "),a={type:"context",itype:(c.cache(a,"params")||{}).type,before:g[0],after:g[2],txt:g[1],loc:location.href,out:c.getActualHref(a),v:2},h.log("info",c.toQuery(a))))};return function(d,e){var f,g,l,h,m=c.context(d)||window;e=d.target||e;e=!e||e===m.name||"_top"===e&&m.top===m||"_parent"===e&&m.parent===m?"_self":e;l=a(m,e);if("_self"!==e&&(!c.traits.crossWindowCommunication||!c.traits.jsRedirectSetsReferrer))h="go";else try{if(void 0===l.document)throw!0;h="jsonp"}catch(p){h="go"}f=c.destructing(c.bind(function(){k.time_click&&
arguments.length&&this.logTime("clk");var a=c.toArray(arguments);a.unshift(d,l,e);this.onApiClick.apply(this,a)},this));c.cache(this,"link","string"===typeof d?d:c.getActualHref(d));if("string"===typeof d&&(d=c.createA(d,e),!this.processLink(d))||!k.enabled)return f();g=this.clickParams(d,h);this.logTime();k.log_context&&b(d);if("go"===h)this.redirect(this.api.now("click",g,{"return":!0}),m,l,e);else if(l===m)this.api.now("click",g,{fn:f,timeout:k.click_timeout});else{if(c.contextIsAncestor(m,l))return this.redirect(c.getActualHref(d),
m,l,e);f=c.exceptionLogger(f);setTimeout(function(){f()},k.click_timeout);l.document.open();l.callback=f;l.document.write("<html><head><title>"+c.getActualHref(d)+'</title><script type="text/javascript" src="'+this.api.now("click",g,{fn:"callback","return":!0})+'">\x3c/script></head></html>');l.document.close()}}}(),clickParams:function(a,b){var d=c.extend(c.cache(a,"params"),{format:b,out:c.getActualHref(a),ref:window.document.referrer||null,reaf:k.reaffiliate||null,title:window.document.title,txt:a.innerHTML});
128<d.txt.length&&(d.txt=d.txt.replace(/<[^>]+>/g,""),d.txt=128<d.txt.length?d.txt.substr(0,125)+"...":d.txt);return d},commonParams:function(a){var b={drKey:k.key?null:k.dr_key,key:k.key,libId:k.library_id};("click"===a||"ping"===a)&&c.extend(b,{cuid:k.cuid,loc:location.href,subId:k.sub_id,v:1},b);return b},detectFiltering:function(){var a;try{a={},a=new function(){this.detect=function(a,b){function c(a,b){0==k||1E3<b?a(0==k&&h):setTimeout(function(){c(a,2*b)},2*b)}function g(){--k||(h=!m&&p)}var h=
!1,k=2,m=!1,p=!1;if("function"==typeof b){a+="?ch=*&rn=*";var u=11*Math.random(),q=new Image;q.onload=g;q.onerror=function(){m=!0;g()};q.src=a.replace(/\*/,1).replace(/\*/,u);q=new Image;q.onload=g;q.onerror=function(){p=!0;g()};q.src=a.replace(/\*/,2).replace(/\*/,u);c(b,250)}}}}catch(b){a={detect:function(a,b){b(!0)}}}return function(b){var e=c.updateUrl(k.asset_url,{pathname:"/images/pixel.gif"});a.detect(e,b)}}(),enabled:function(){if(k.enabled&&n!==window&&window.vglnk&&(window.vglnk.key||"function"===
typeof window.vglnk))k.enabled=!1;return k.enabled},expose:function(a,b){if(b=b||this[a])"function"===typeof b?b=c.exceptionLogger(c.bind(b,this)):"object"===typeof b&&(b=c.clone(b)),t[a]||(t[a]=b)},fire:function(){var a={};return function(b,d){b=b.toLowerCase();var e=a[b]||{fired:!1,listeners:[]};"function"===typeof d?e.fired?setTimeout(function(){d({type:b})},0):e.listeners.push(d):(e.fired=!0,c.each(e.listeners,function(a){"function"===typeof a&&a({type:b})}),e.listeners=[]);a[b]=e}}(),handleRightClick:function(a,
b){if(k.rewrite_modified&&a&&b)switch(b){case "setup":c.cache(a,"href")||c.cache(a,"href",a.href);a.href=this.api.now("click",this.clickParams(a,"go"),{"return":!0});setTimeout(c.exceptionLogger(c.bind(function(){this.handleRightClick(a,"teardown")},this)),0);break;case "teardown":a.href=c.cache(a,"href"),c.cache(a,"href",null)}},harmony:function(){c.harmony={UNSAFE_QUIRKSMODE_HANDLERS:0,LINK_LEVEL_EVENTS:-1};return function(a){return k.harmony_level<=a}}(),init:function(){var a=function(){var a=
!0===window.document.__v5k;window.document.__v5k=!0;return!a};return function(){var b=this;r={};if(a()){try{b.initLibEvents(),b.initNamespace(),b.initOptions()}catch(d){}c.exceptionLogger(c.bind(b.logException,b),!k.dev);return c.exceptionLogger(function(){b.initProcessors();b.initDRApi();b.initApi();b.enabled()&&(b.initLegacyCallbacks(),b.ping())})()}}}(),initApi:function(){var a,b={};if(window.vglnk)for(a in window.vglnk)"_plugin"===a.substr(-7)&&(b[a]=window.vglnk[a]);t=n[m]=c.noop;this.expose("click");
this.expose("link",c.bind(function(a){"element"===c.type(a)&&a.href&&(this.initContext(c.context(a)),this.processLink(a))},this));this.expose("open",c.bind(this.click,this));this.expose("$",c.clone(c));this.expose("api");this.expose("opt");this.expose("registerProcessor",function(){if(0<arguments.length)return h.registerProcessor.apply(h,arguments)});c.extend(t,t===window.vglnk?b:{})},initContext:function(){var a=[];return function(b){if(void 0===b)return a;b&&!c.contains(a,b)&&(a.push(b),this.initLinks(b),
this.initEvents(b))}}(),initDRApi:function(){var a=!1;window.DrivingRevenue=c.exceptionLogger(c.destructing(c.bind(function(){a=!0;k.dr_key=window.DR_id;this.enabled()&&this.ping()},this)));c.on("DOMReady",function(){if(!a)try{delete window.DrivingRevenue}catch(b){window.DrivingRevenue=void 0}})},initEvents:function(a){var b={left:h.onClick,right:h.onContextmenu},d={left:c.noop,right:c.noop},e=c.traits.windowLevelHandlers?a:a.document,f=function(e){e=e||a.event;if((e=c.eventLink(e))&&!c.cache(e,"evented"))g(e,
h.harmony(c.harmony.LINK_LEVEL_EVENTS)?b:d),c.cache(e,"evented",!0)},g=function(a,b){c.on(a,"click",c.bind(b.left,h));c.on(a,"contextmenu",c.bind(b.right,h))};c.on(e,"copy",c.bind(h.onCopy,h));c.on(e,"mousedown",f);if(h.harmony(c.harmony.LINK_LEVEL_EVENTS))c.on("DOMReady",function(){c.each(a.document.links,function(a){c.on(a,"mousedown",f)})});(!c.traits.quirksMode||h.harmony(c.harmony.UNSAFE_QUIRKSMODE_HANDLERS))&&g(e,b)},initLegacyOptions:function(){var a,b={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",
vglnk_domain:"api_url",vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(a in b)void 0!==window[a]&&(t[b[a]]=window[a],"vglnk_domain"===a&&(t[b[a]]+="/api"))},initLegacyCallbacks:function(){var a,b={vl_cB:c.bind(this.onApiClick,this),vl_disable:function(){k.enabled=!1}};for(a in b)window[a]=b[a]},initLibEvents:function(){c.on(h);c.ready(c.bind(function(){this.fire("DOMReady")},this))},initLinks:function(a){var b=c.bind(function(a){c.each(c.toArray(a.document.links),c.bind(this.processLink,this))},
this);void 0===a?c.each(this.initContext(),b):b(a)},initNamespace:function(){window.vglnk&&window.vglnk.key&&(m="vglnk");var a=window,b=m.split("."),c;for(m=b.pop();0<b.length;)c=b.shift(),a[c]=a[c]||{},a=a[c];n=a;t=n[m]=n[m]||{}},initOptions:function(){var a;this.initLegacyOptions();k=c.extend(this.publicOptions({api_url:"//api.viglink.com/api",asset_url:"//cdn.viglink.com/api",cuid:null,dev:!1,dr_key:null,enabled:c.traits.basicCompatibility,key:null,link_urls:!0,partner:null,sub_id:null,reaffiliate:!1,
commercial:null,harmony_level:0,rewrite_modified:!1,rewrite_original:!0}),k,t,{click_timeout:1E3,hop_timeout:2E3,debug:!1,library_id:null,log_context:!0,nofollow:{},norewrite:{},plugins:{link_affiliation:{},modified_clicks:{},partner_integration:{}},time_click:!1,time_ping:!1,testing_js:[]});for(a in k)"_plugin"===a.substr(-7)&&delete k[a]},initPlugins:function(){var a,b=1,d={link_affiliation:"convert",link_optimization:"optimize",partner_integration:"partners",product_linker:"insert",product_widget:"spotlight"},
e=["spotlight"],f=function(c){return function(c){return function(){delete r[c].opts.mode;b=1;clearTimeout(a);l()}}(c)},g=function(a){var b;c.find(d,function(a,c){return"insert"===a&&(b=c)});a[b]||(a[b]={enabled:!0,key:k.key,link_phrases:!1});a[b].link_urls=k.link_urls;return a},l=function(){var d=!1,e=function(a){return function(){if(a){var b=c.toArray(arguments);b.unshift("custom",a);h.log.apply(this,b)}}};a=null;c.each(r,function(a,b){a.ran||(!a.setup&&window.vglnk&&(a.setup=window.vglnk[b+"_plugin"]),
a.setup?(!a.run&&"function"===c.type(a.setup)&&(a.run=a.setup(a.opts,c.clone(c),t,e(a.opts.key||k.key))||c.noop),a.opts.mode!==h.PLUGIN_MANUAL&&h.runPlugin(b)):d=!0)});d&&(a=setTimeout(c.exceptionLogger(l),Math.min(Math.max(Math.pow(2,++b),100),5E3)))},m=function(){setTimeout(function(){h.api.flush()},100);l();c.on("DOMReady",function(){setTimeout(h.api.flush,0)})};return function(a){a=g(a);c.each(a,c.bind(function(a,b){b=d[b]||b;"object"===typeof a&&!1!==a.enabled&&(r[b]={opts:a},c.contains(e,b)&&
c.jsonp(this.opt("asset_url")+"/plugins/"+b+".js"),a.mode===this.PLUGIN_MANUAL&&this.expose("init_"+b,f(b)))},this));m()}}(),initProcessors:function(){this.registerProcessor(function(a){var b;b=c.createA(k.api_url);if("/api/click"===a.pathname&&(a.hostname===b.hostname||a.hostname.match(/(^|\.)(api|cdn|apicdn)\.viglink\.com$/)))b=c.fromQuery(a.search),void 0!==b.out&&(a.href=b.out,delete b.out,c.cache(a,"params",b))});this.registerProcessor(function(a){k.nofollow[a.href]&&!c.hasRel(a,"nofollow")&&
(a.rel=(a.rel?a.rel+" ":"")+"nofollow")});this.registerProcessor(function(a){window.IPBoard&&(window.IPBoard.prototype&&window.IPBoard.prototype.delegate&&c.hasRel(a,"external"))&&(a.rel=a.rel.replace(/(^| )external( |$)/,""),a.target="_blank")})},isRewritable:function(){var a=c.canonicalizeHostname(document.location),b=c.generateNodeFilter({rels:["norewrite","noskim"],custom:function(b){var e,f="";try{e=b.hostname,f=b.protocol,e.charAt(0)}catch(g){return!0}""!==e&&(e=c.canonicalizeHostname(b));return""===
e||a===e||"object"===c.type(k.commercial)&&!k.commercial[e]||!f.match(/^https?:$/i)||k.norewrite[e]||!(k.rewrite_original||c.cache(b,"type"))}});return function(a){return b(a,{ancestors:!1})}}(),log:function(a,b,d,e){var f,g=c.toQuery({libId:k.library_id,nocache:c.uniqid()});f="pixel.gif";if("custom"===a)g+="&"+c.toQuery({key:b,type:d}),c.each("array"===c.type(e)?e:[e],function(a){c.each(["e","i","o"],function(b){delete a[b]});g+="&"+c.toQuery(a)});else{g+="&"+c.toQuery({key:k.key,drKey:k.key?null:
k.dr_key});if("time"===a)f="time.gif",a={time:d,type:b};else if("exception"===a)a={e:b,o:d};else if("info"===a)a={i:b};else return;g+="&"+c.toQuery(a)}f=k.api_url+"/"+f+"?"+g;c.transmitsPII(f)||(c.createEl("img").src=f)},logException:function(a){if(k.debug){var b={link:c.cache(this,"link"),loc:document.location.href,UA:navigator.userAgent};"string"===typeof a?b.message=a:b=c.extend(b,a);this.log("exception",a,c.toQuery(b))}},logTime:function(){var a;return function(b){0===arguments.length?a=(new Date).getTime():
this.log("time",b,(new Date).getTime()-a)}}(),onApiClick:function(a,b,d,e,f){var g=e||c.getActualHref(a),h=c.bind(function(){this.redirect(g,c.context(a),b,d)},this);"object"===typeof f&&(f.tracking||f.image)?(e=c.createEl(f.tracking?"iframe":"img",{src:f.tracking||f.image},{height:0,width:0,visibility:"hidden"}),document.body.appendChild(e),setTimeout(c.exceptionLogger(h),f.timeout||k.hop_timeout)):h()},onApiPing:function(a,b,d,e,f,g){k.rewrite_original=!1;f=c.reformatKeys(f||{});var l,m;e=function(a){var b=
{},d=function(a){c.isArray(a)?b[a[0]]=a[1]:b[a]=1};c.isArray(a)&&c.each(a,d);return b};m=c.extend(k.plugins,f.plugins);k=c.extend(k,f);delete k.plugins;k.library_id=a;k.click_timeout=b;k.time_ping&&this.logTime("png");"array"===c.type(k.testing_js)&&0<k.testing_js.length&&c.each(k.testing_js,function(a){c.jsonp(a)});c.extend(k.norewrite,e(d));c.extend(k.nofollow,e(g));for(l in k)"on"===l.toLowerCase().substr(0,2)&&(2<l.length&&"function"===c.type(k[l]))&&(c.on(h,l.toLowerCase().substr(2),c.bind(k[l],
window)),delete k[l]);this.initPlugins(m);this.initContext(window);this.fire("libready")},onClick:function(a){a=a||window.event;var b=a.ctrlKey||a.metaKey||a.altKey||a.shiftKey,d=a.which&&1===a.which||0===a.button,e=c.eventLink(a);if(e&&this.isRewritable(e)&&!b&&d&&!c.isDefaultPrevented(a))return this.click(e),c.preventDefault(a)},onContextmenu:function(a){(a=c.eventLink(a||window.event))&&this.isRewritable(a)&&this.handleRightClick(a,"setup")},onCopy:function(a){var b,d,e,f=[];if(window.getSelection){d=
window.getSelection();a=0;for(b=d.rangeCount;a<b;a++){try{e=d.getRangeAt(a).toString().replace(/((^)\s+|\s+$|\r)/g,"").replace(/\s*\n\s*/g,"\n")}catch(g){}0<e.length&&128>=e.length&&f.push(e)}}c.each(f,function(a){h.log("info",c.toQuery({type:"selection",txt:a,loc:location.href}))})},opt:function(a,b){void 0!==b&&void 0!==this.publicOptions()[a]&&(k[a]=b);return k[a]},ping:function(){var a=!1;return function(){if(!a&&(k.key||k.dr_key)){var b={ref:document.referrer||null};a=!0;c.transmitsPII(this.api.now("ping",
b,{"return":!0}))||(this.logTime(),this.detectFiltering(c.bind(function(a){a&&(b.type=this.TYPE_ACCEPTABLE);this.api.now("ping",b,{fn:c.bind(this.onApiPing,this)})},this)))}}}(),processLink:function(a){if(this.isRewritable(a)){var b=c.cache(a,"processors")||{};c.each(this.registerProcessor(),function(c){b[c.id]||c.fn(a);b[c.id]=!0});c.cache(a,"processors",b);return a}},publicOptions:function(){var a={};return function(b){"object"===c.type(b)&&(a=b);return c.extend({},a)}}(),redirect:function(a,b,
d,e){b=b||window.top;!c.traits.crossWindowCommunication&&!d?(e=b.open(a,e),e.focus()):c.traits.jsRedirectSetsReferrer?setTimeout(c.exceptionLogger(function(){!d||d===b?b.location=a:c.contextIsAncestor(b,d)?d.location=a:d.location.replace(a)}),0):("_blank"===e&&(e=c.uniqid("win_")),e=c.createA(a,e),e.rel="norewrite",b.document.body.appendChild(e),e.click(),e.parentNode.removeChild(e))},runPlugin:function(a,b){var d=r[a];d&&(b=b||[document.body],"function"===c.type(d.run)&&(c.each(b,function(a){d.run(a)}),
d.ran=!0))},registerProcessor:function(){var a=!1,b=[],d=function(d){if(void 0===d)return b;"function"===c.type(d)&&(b.push({id:c.uniqid(),fn:d}),a&&this.initLinks())};d(function(){a=!0});return d}()};h.init();try{delete window.vglnk_self}catch(C){}})("undefined"===typeof vglnk_self?"vglnk":vglnk_self);window.vglnk=window.vglnk||{};
window.vglnk.convert_plugin=function(m,h,c){var w={},k;m=h.extend({any:!0},m);k={getDomains:function(){var m=[];h.each(w,function(c,h){m.push(h)});0<m.length&&c.api("domains",{domains:m.join("|")},{fn:h.bind(k.onDomainApi,k)})},initDomainLookup:function(){var c=!1;return function(){c||(c=!0,h.on("DOMReady",h.bind(this.getDomains,this)))}}(),onDomainApi:function(k){var m;"object"===h.type(k)&&"array"===h.type(k.results)&&(m={},h.each(k.results,function(c){m[c]=!0}),c.opt("commercial",m))},saveDomain:function(c){c=
h.canonicalizeHostname(c);w[c]=!0},setup:function(){c.opt("rewrite_original",!0);m.any||c.registerProcessor(function(c){k.initDomainLookup();k.saveDomain(c)})}};return function(){k.setup()}};window.vglnk=window.vglnk||{};window.vglnk.modified_clicks_plugin=function(m,h,c){return function(){c.opt("rewrite_modified",!0)}};window.vglnk=window.vglnk||{};
window.vglnk.partners_plugin=function(m,h){var c="https:"===document.location.protocol,w={setup:function(){window._comscore=window._comscore||[]},run:function(){var k=window._comscore;k&&"function"===h.type(k.push)&&(k.push({c1:8,c2:17570528,c3:1}),h.jsonp("//"+(c?"sb":"b")+".scorecardresearch.com/beacon.js"))}};w.setup();return function(){w.run()}};window.vglnk=window.vglnk||{};
window.vglnk.dr_search_box_plugin=function(m,h,c){m=h.extend({key:null},m);var w={init:function(){h.each(this.getDRSearchForms(),function(c){if(!h.cache(c,"evented")){var m=w.getInput(c),n=function(){m.value||h.css(m,{"background-image":"url(http://cdn.viglink.com/images/ebay_watermark.gif)"})};h.cache(c,"evented",!0);c.onsubmit=null;m.onfocus=null;m.onblur=null;h.on(m,"focus",function(){h.css(m,{"background-image":"none"})});h.on(m,"blur",n);n();h.on(c,"submit",function(h){w.onSubmit(h,c)})}})},
getDRSearchForms:function(){var c=[];h.each(document.getElementsByTagName("form"),function(h){w.getInput(h)&&h.id.match(/^DR-ebay-search(CSS|2)?$/i)&&c.push(h)});return c},getInput:function(c){return c.p||c.q2},onSubmit:function(k,r){k=k||window.event;var n="http://shop.ebay.com/i.html?"+h.toQuery({_nkw:w.getInput(r).value}),n=h.createA(n,"_blank");h.cache(n,"params",{key:m.key});c.click(n);return h.preventDefault(k)}};return function(){m.key&&(w.init(),h.on("DOMReady",h.bind(w.init,w)))}};
window.vglnk=window.vglnk||{};
window.vglnk.optimize_plugin=function(m,h,c,w){var k,r={},n=0;m=h.extend({platform:null},m);k={getLinks:function(){var t=h.platforms(m.platform).getPostIDs();c.api("optimize",{pt:m.platform,i:t?t.join("|"):null,u:location.href},{fn:h.bind(k.onOptimizeApi,k)})},log:function(){w("optimize",{ct:n})},onOptimizeApi:function(c){"object"===h.type(c)&&"object"===h.type(c.optLinks)&&(r=c.optLinks,this.optimizeLinks({data:!0}))},optimizeLink:function(){var c=h.generateNodeFilter({classes:["nooptimize"],rels:["nooptimize"],
custom:function(a,b){if(b)return Boolean(h.cache(a,"type"))}}),k=function(a){var b=a.href,c=a.textContent||a.innerText,e=function(){var b=h.canonicalizeHostname(a);return h.canonicalizeHostname(h.createEl("a",{href:c}))===b},f=function(){var b;return e()?(b=h.fromQuery(a.search),h.find(b,function(a){return a===c})):!1};return{exact:b===c||function(){var a=c.split(/(?:\.\.\.|\u2026)/);return 2>a.length?!1:RegExp("^"+h.map(a,h.escapeRegExp).join(".+")+"$").test(b)}()||f(),partial:function(){var b=h.canonicalizeHostname(a);
return RegExp("\\b"+h.escapeRegExp(b)+"\\b","i").test(c)}()||-1!==c.indexOf(b)}};return function(a){var b,d=r[a.href];if(d&&c(a)){b=k(a);if(b.exact){b=d.frdLink||d.optLink;for(var e;e=a.firstChild;)a.removeChild(e);a.appendChild(document.createTextNode(b))}else if(b.partial)return;h.cache(a,"params",{type:"LO",origOutId:d.pcid+":"+d.linkId});a.href=d.optLink;n++}}}(),optimizeLinks:function(){var m={data:!1,timing:!1};return function(n){m=h.extend(m,n);m.timing&&(m.data&&r)&&(c.registerProcessor(h.bind(this.optimizeLink,
k)),setTimeout(function(){k.log()},0))}}(),setup:function(){if(!m.platform||"full"===m.platform)this.getLinks();else h.on("DOMReady",h.bind(this.getLinks,this))}};k.setup();return function(){h.on("DOMReady",function(){k.optimizeLinks({timing:!0})})}};window.vglnk=window.vglnk||{};window.vglnk.page_harmony_plugin=function(m,h,c){m=h.extend({level:null},m);return function(){var h=parseInt(m.level,10);isFinite(h)&&c.opt("harmony_level",h)}};window.vglnk=window.vglnk||{};
window.vglnk.insert_plugin=function(m,h,c,w){var k,r,n=null,t={},C,a=0,b=0,d=0;m=h.extend({cat:null,platform:null,key:null,link_phrases:!0,link_urls:!0,link_target:null,per_page:null,per_phrase:5,product_source:null,proximity:null,same_proximity:100,scope:null,type:null,ui:!0},m);if(m.key)return k=h.platforms(m.platform),r={addPhrasesToMatcher:function(a){var b="";"regexp"===h.type(a)?b=a.source:"array"===h.type(a)&&(b="(?:^|[\\s\"'\\(])("+h.map(a,function(a){return h.escapeRegExp(a).split(" ").join("\\s+")}).join("|")+
")(?=\\s|\\W*$|\\W{2})");""!==b&&(C=RegExp(C?"(?:"+b+"|"+C.source+")":b,"i"))},focusLink:function(a){a.id||(a.id=h.uniqid("vl-link-"));location.href.hash="#"+a.id;window.scrollBy(0,-150)},getPhrases:function(){var a=k.getPostIDs();c.api("insert",h.extend(r.getPartnerParams(),{cat:m.cat,mode:m.mode,pt:m.platform,ps:m.product_source,i:a?a.join("|"):null,u:location.href,type:m.type}),{fn:h.bind(r.onInsertApi,r)})},getPartnerParams:function(){var a,b,d=c.opt("partner"),h={};for(a in d)break;if(a)for(b in d[a])h[a+
"_"+b]=d[a][b];return h},initLink:function(a,b,d){if(d=m.link_target||d)a.target=d;a.rel="nofollow";a.href||(a.href=b.url);h.cache(a,"params",{exp:n,key:m.key,mid:b.mid,type:b.type||null});h.cache(a,"href",a.href);c.link(a)},insertLinks:function(){var c={data:m.link_phrases?!1:m.link_urls,timing:!1},f=function(a,b){var c;c=h.createEl("a");c.innerHTML=a.replace(/([a-z0-9]+ *|[^a-z0-9]+)/ig,"<span>$1</span>");c.className="vglnk";h.cache(c,"type","inserted");h.cache(c,"phrase",a);m.ui&&(c.title="Link added by VigLink");
r.initLink(c,b);return c},g=function(c,e){for(var g,k,l,n,w=function(b){var c;b=!b||!m.per_phrase||!b.count||b.count<m.per_phrase;c=!m.per_page||a<m.per_page;return b&&c},x=function(a,b){var c,d,e,f,g,k,l,p,n,u,q=function(b){n.parentNode.insertBefore(a,n);n.parentNode.removeChild(n);return b},r=function(a,b,c){a=h.extend({},a);a.x1-=c;a.y1-=c;a.x2+=c;a.y2+=c;return a.x1<b.x2&&a.x2>b.x1&&a.y1<b.y2&&a.y2>b.y1};n=h.createEl("span");a.parentNode.insertBefore(n,a);n.appendChild(a);u=h.geometry(n);if(m.proximity||
m.same_proximity)for(k in t)if((l=t[k].links)&&!(t[k]===b&&!m.same_proximity||t[k]!==b&&!m.proximity)){p=t[k]===b?Math.max(m.same_proximity,m.proximity):m.proximity;c=0;for(d=l.length;c<d;c++){g=l[c].segments;e=0;for(f=g.length;e<f;e++)if(r(g[e].geometry,u,p))return q(!1)}}return q(!0)},Y=function(a,b){var c,d,e,f,g={el:a,segments:[]},k=a.getElementsByTagName("span"),l={els:[]};c=0;for(d=k.length;c<d;c++)e=k[c],void 0===f||e.offsetTop===f.offsetTop?l.els.push(e):(g.segments.push(l),l={els:[e]}),f=
e;l.geometry=h.geometry.apply(h,l.els);g.segments.push(l);b.links=b.links||[];b.links.push(g);return b};c&&c.data&&(Boolean(l=c.data.match(/^\s+/))||Boolean(l=c.data.match(C)));)k=l[0],n=l.slice(1).join(""),g=t[r.normalizePhrase(n)],k=c.data.indexOf(k)+k.length-n.length,0<k&&(c=c.splitText(k)),k=c.length<=n.length?null:c.splitText(n.length),n&&!g&&(g={url:n.match(/^https?:\/\//i)?n:"http://"+n,type:"U"}),g&&(g.url.match(/https?:\/\//i)&&n&&w(g)&&x(c,g))&&(n=f(n,g),h.cache(n,"unlinked")||("L"===g.type.toUpperCase()?
b++:d++,e(n,c),Y(n,g),g.count++,a++)),c=k},l=function(a){var b=!1,c=a.parentNode,d=function(a,b){c.insertBefore(a,b);c.removeChild(b)};a.data&&(b=C.test(a.data.replace(/\s+/," ")));b&&g(a,d)},k=h.generateNodeFilter({classes:["nolinks","atma-nolink","atma-nolinks"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" "),custom:function(a){return h.matches(a,"a[href]")}}),n=function(a){var b;if(a){if(k(a,{ancestors:!1,self:!0}))for(b=
a.firstChild;b;)a=b.nextSibling,1===b.nodeType?n(b):3===b.nodeType&&l(b),b=a}else h.each(h.select(m.scope),function(a){k(a,{ancestors:!0,self:!1})&&n(a)})};return function(a){c=h.extend(c,a);c.timing&&(c.data&&C)&&(n(),m.link_phrases&&r.log())}}(),loadPhrases:function(a){var b,c,d,h=[];b=0;for(c=a.length;b<c;b++)d=a[b],d.phrase&&d.url&&(d.phrase=this.normalizePhrase(d.phrase),t[d.phrase]||(h.push(d.phrase),t[d.phrase]={count:t[d.phrase]?t[d.phrase].count:0,phrase:d.phrase,mid:d.mid,url:d.url,type:d.type||
""}));0<h.length&&this.addPhrasesToMatcher(h);this.insertLinks({data:!0})},log:function(){var c,f,g={heavy:[],lite:[]},h=function(a,b){return b.split(",")[0]-a.split(",")[0]};for(c in t)f=parseInt(t[c].count,10),0<f&&(f=[f,c.replace(/\|/g,"%7C")].join(),g["L"===t[c].type.toUpperCase()?"lite":"heavy"].push(f));g.lite.sort(h);g.heavy.sort(h);w("insert",[{ct:a,cl:b,ch:d,cu:0,exp:n},{pl:g.lite.join("|")},{ph:g.heavy.join("|")}])},onInsertApi:function(a){"object"===h.type(a)&&(n=a.exp,a.results&&this.loadPhrases(a.results))},
normalizePhrase:function(a){return a.toLowerCase().replace(/(^\s+|\s+$)/g,"").split(/\s+/).join(" ")},setup:function(){m.scope=m.scope||k.scope||"body";m.link_urls&&this.addPhrasesToMatcher(RegExp("(?:(?:\\b(https?://)|(?:^|\\s)\\W*(www\\d{0,3}\\.|(?:[a-z0-9-]+\\.)+[a-z]{2,4}/))((?:[^\\s()<>]+|\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\))+(?:\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\)|[^\\s`!()\\[\\]{};:'\".,<>?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|(?:^|\\s)\\W*((?:[a-z0-9-]+\\.)+com(?:/|\\b)))",
"i"));if(m.link_phrases)if(!m.platform||"full"===m.platform)this.getPhrases();else h.on("DOMReady",h.bind(this.getPhrases,this))}},r.setup(),function(){h.on("DOMReady",function(){r.insertLinks({timing:!0})})}};
